//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/AllInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AllInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AllInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AllInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fd5ff348-ba22-4dd7-a578-d0d92f7017fb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""98709ac0-92e0-4075-9398-4e7ce53a96b6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""35bba937-edd5-419d-a413-717cc2c360b6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""c3d98919-0222-4b89-b6e0-2e588c14bdf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""b28bd2a5-3471-4750-8338-b8a7e15bcc9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""cdf8bec4-8c19-4323-9386-fb5009da8ac2"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""40a28db1-52ba-4d17-8304-cceae3e67fcb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8ff0f989-8f9a-4599-8f4d-8081103786d6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0b75605c-fae8-4cbb-995d-b626e346172c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5f35819d-e6e4-4e3a-a04f-495496023a4a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b8d1da25-4715-447f-80fb-4534307ea127"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse;Touch"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""595c0452-db08-4b89-8a3a-4c942de52c15"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b50e3530-d02d-4cc1-a459-3c6e65876941"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""ea5e6531-5e7b-4160-ba1b-737d2e93627a"",
            ""actions"": [
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""bbbdfbb5-7cc8-4370-b149-b60270d70e09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crafting"",
                    ""type"": ""Button"",
                    ""id"": ""a133d034-1aa3-44cd-b35f-4bacaf46c22a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""76242cf4-0b90-4b15-917f-a4ea770f92ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""39826552-bc06-427b-bb9c-5cffe398bc66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c9019eb9-46e8-463a-af62-a70f194b04cf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7eae317e-2c3c-4df9-9e5b-43a22ebb1e1e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crafting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d5d9193-b8ee-4d5a-852b-7f152e3117a5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dd3aade-4d04-4b32-9271-89ac9b19569a"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Mouse"",
            ""id"": ""8380ef59-acf5-445e-ba2b-b10bebda90ce"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""6acc7c1b-5e2c-43b8-91c0-cb74ab05d90c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""e5486c4a-48bc-4005-8d2b-d3f0dece0e36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartClick"",
                    ""type"": ""Button"",
                    ""id"": ""cd91ce6b-718f-42cd-b9fd-72cfd72cb1ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EndClick"",
                    ""type"": ""Button"",
                    ""id"": ""41e031c7-ff29-402c-b136-7843c3a039d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a36eaa86-1d0b-4fec-8d4e-fef43d537669"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b606e83-a536-49ec-8581-8ac99fe46f64"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8124ecf-f64f-4e9b-ad58-4da05142da29"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a23da263-3560-473b-a3d3-8e431d08bc0c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EndClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""id"": ""f60df8ad-4b51-4be7-af8d-994f7b8aef27"",
            ""actions"": [
                {
                    ""name"": ""add"",
                    ""type"": ""Button"",
                    ""id"": ""4ff23081-2c5e-4fa5-9094-2d5e49db5374"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""remove"",
                    ""type"": ""Button"",
                    ""id"": ""e2197d43-ca26-43b4-83ae-603f61b6f56b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""512b2ce8-a60f-40c9-b0ef-e30ef8ae01e3"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""add"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d923505e-82f9-474f-9c78-f26c2bba8476"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BuildMode"",
            ""id"": ""4e6a0b3d-3c1c-429c-be2f-0180acd01413"",
            ""actions"": [
                {
                    ""name"": ""remove"",
                    ""type"": ""Button"",
                    ""id"": ""5ff5cc61-5b4b-42fb-ae77-c6ad0517f261"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""add"",
                    ""type"": ""Button"",
                    ""id"": ""8800f7de-835d-48de-a921-83e7462bac69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotate"",
                    ""type"": ""Button"",
                    ""id"": ""e3720cbd-4dd6-42c7-b161-34ed09d20b5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""delete"",
                    ""type"": ""Button"",
                    ""id"": ""127a1077-0c35-44cf-a1c4-7758af0611be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""changeCell"",
                    ""type"": ""Value"",
                    ""id"": ""08218c32-8c53-4e9a-b4d9-ef99fe6bc2e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9aa3ea45-8588-4e0b-bfc3-cf7f41125257"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""add"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""back tab"",
                    ""id"": ""c3456742-1064-4ddc-af8b-099c10297ffd"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""remove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4196868e-4211-499b-b165-e99e1725b943"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0cdbf5ba-2334-4544-8f26-52cf908401ca"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5987b795-f56e-4e73-b1f8-70a7372cb7d5"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f50a6d8-e84f-4537-94fc-444d00fff731"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f35eef11-1fed-4cc8-9d5b-5d1c59c9e5b5"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d924c9e-bf28-451d-9b55-2faa0b52848a"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ArrowKey"",
                    ""id"": ""65bd5286-a5d3-4967-a431-208a39d33a8b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeCell"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9d314167-230f-48ae-a6c6-c2b2832ce6e5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeCell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""70473df4-fbe8-499e-ba2e-fe224143ae1f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeCell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bee3e0b6-37a4-4459-a4e9-3738b2f514f0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeCell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d1d8a6f8-f4f5-4ea3-b678-c806e42d3955"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeCell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""b0c9af96-cd2f-490d-bf41-1194a756bb7f"",
            ""actions"": [
                {
                    ""name"": ""action0"",
                    ""type"": ""Button"",
                    ""id"": ""952203f2-e6f2-47a3-8025-f1b103d4e7fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action1"",
                    ""type"": ""Button"",
                    ""id"": ""21bd3683-6f98-440c-88cc-7b5b5b69a61c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action2"",
                    ""type"": ""Button"",
                    ""id"": ""f2a9c047-5baf-4fef-bdcd-b0d1cf78a796"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action3"",
                    ""type"": ""Button"",
                    ""id"": ""47d3e600-146b-4f09-90c6-0982b69fdb46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action4"",
                    ""type"": ""Button"",
                    ""id"": ""942b06b7-bd8f-4f39-8028-2190c7f7bec8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action5"",
                    ""type"": ""Button"",
                    ""id"": ""f1e4c5fe-97e3-466f-928d-b1073bc2098a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action6"",
                    ""type"": ""Button"",
                    ""id"": ""453ba28b-12f4-4b72-95c8-dd8ac8748a9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action7"",
                    ""type"": ""Button"",
                    ""id"": ""d0e79707-8976-48f3-8ccc-3116c4a55634"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action8"",
                    ""type"": ""Button"",
                    ""id"": ""8d5a7fe1-87fd-454f-9170-1c83bbb70863"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action9"",
                    ""type"": ""Button"",
                    ""id"": ""fb29bb67-3e57-4a30-ae67-cd736167255d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7541df29-9371-49cc-b303-65725830f5a8"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""419b489a-4c0e-4d12-8da0-976cff2ea3e2"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""712438f3-2082-46dd-8e74-7d263b6f2142"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7319cc7-ea1c-4570-85f1-b58a837010e5"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93791759-d042-4e32-ae69-4ffd82c5ed5d"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1360e4c-5287-46be-aa62-ba148af9fb45"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e8b197-4180-4e1a-8b03-d6f049b82a58"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2558f4bc-42c1-4bf1-a795-83e9d53e39cf"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""295116b6-c18a-4e21-ab6f-7a337c59dc37"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c313de97-85ac-425f-b112-7ae8efb20514"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Inventory = m_UI.FindAction("Inventory", throwIfNotFound: true);
        m_UI_Crafting = m_UI.FindAction("Crafting", throwIfNotFound: true);
        m_UI_PauseMenu = m_UI.FindAction("PauseMenu", throwIfNotFound: true);
        m_UI_BuildMode = m_UI.FindAction("BuildMode", throwIfNotFound: true);
        // Mouse
        m_Mouse = asset.FindActionMap("Mouse", throwIfNotFound: true);
        m_Mouse_Position = m_Mouse.FindAction("Position", throwIfNotFound: true);
        m_Mouse_Click = m_Mouse.FindAction("Click", throwIfNotFound: true);
        m_Mouse_StartClick = m_Mouse.FindAction("StartClick", throwIfNotFound: true);
        m_Mouse_EndClick = m_Mouse.FindAction("EndClick", throwIfNotFound: true);
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_add = m_Keyboard.FindAction("add", throwIfNotFound: true);
        m_Keyboard_remove = m_Keyboard.FindAction("remove", throwIfNotFound: true);
        // BuildMode
        m_BuildMode = asset.FindActionMap("BuildMode", throwIfNotFound: true);
        m_BuildMode_remove = m_BuildMode.FindAction("remove", throwIfNotFound: true);
        m_BuildMode_add = m_BuildMode.FindAction("add", throwIfNotFound: true);
        m_BuildMode_rotate = m_BuildMode.FindAction("rotate", throwIfNotFound: true);
        m_BuildMode_delete = m_BuildMode.FindAction("delete", throwIfNotFound: true);
        m_BuildMode_changeCell = m_BuildMode.FindAction("changeCell", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_action0 = m_Debug.FindAction("action0", throwIfNotFound: true);
        m_Debug_action1 = m_Debug.FindAction("action1", throwIfNotFound: true);
        m_Debug_action2 = m_Debug.FindAction("action2", throwIfNotFound: true);
        m_Debug_action3 = m_Debug.FindAction("action3", throwIfNotFound: true);
        m_Debug_action4 = m_Debug.FindAction("action4", throwIfNotFound: true);
        m_Debug_action5 = m_Debug.FindAction("action5", throwIfNotFound: true);
        m_Debug_action6 = m_Debug.FindAction("action6", throwIfNotFound: true);
        m_Debug_action7 = m_Debug.FindAction("action7", throwIfNotFound: true);
        m_Debug_action8 = m_Debug.FindAction("action8", throwIfNotFound: true);
        m_Debug_action9 = m_Debug.FindAction("action9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Fire;
    private readonly InputAction m_Player_Run;
    public struct PlayerActions
    {
        private @AllInput m_Wrapper;
        public PlayerActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Run.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Inventory;
    private readonly InputAction m_UI_Crafting;
    private readonly InputAction m_UI_PauseMenu;
    private readonly InputAction m_UI_BuildMode;
    public struct UIActions
    {
        private @AllInput m_Wrapper;
        public UIActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Inventory => m_Wrapper.m_UI_Inventory;
        public InputAction @Crafting => m_Wrapper.m_UI_Crafting;
        public InputAction @PauseMenu => m_Wrapper.m_UI_PauseMenu;
        public InputAction @BuildMode => m_Wrapper.m_UI_BuildMode;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Inventory.started -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Crafting.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCrafting;
                @Crafting.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCrafting;
                @Crafting.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCrafting;
                @PauseMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseMenu;
                @BuildMode.started -= m_Wrapper.m_UIActionsCallbackInterface.OnBuildMode;
                @BuildMode.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnBuildMode;
                @BuildMode.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnBuildMode;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Crafting.started += instance.OnCrafting;
                @Crafting.performed += instance.OnCrafting;
                @Crafting.canceled += instance.OnCrafting;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
                @BuildMode.started += instance.OnBuildMode;
                @BuildMode.performed += instance.OnBuildMode;
                @BuildMode.canceled += instance.OnBuildMode;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Mouse
    private readonly InputActionMap m_Mouse;
    private IMouseActions m_MouseActionsCallbackInterface;
    private readonly InputAction m_Mouse_Position;
    private readonly InputAction m_Mouse_Click;
    private readonly InputAction m_Mouse_StartClick;
    private readonly InputAction m_Mouse_EndClick;
    public struct MouseActions
    {
        private @AllInput m_Wrapper;
        public MouseActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_Mouse_Position;
        public InputAction @Click => m_Wrapper.m_Mouse_Click;
        public InputAction @StartClick => m_Wrapper.m_Mouse_StartClick;
        public InputAction @EndClick => m_Wrapper.m_Mouse_EndClick;
        public InputActionMap Get() { return m_Wrapper.m_Mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void SetCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnPosition;
                @Click.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnClick;
                @StartClick.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnStartClick;
                @StartClick.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnStartClick;
                @StartClick.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnStartClick;
                @EndClick.started -= m_Wrapper.m_MouseActionsCallbackInterface.OnEndClick;
                @EndClick.performed -= m_Wrapper.m_MouseActionsCallbackInterface.OnEndClick;
                @EndClick.canceled -= m_Wrapper.m_MouseActionsCallbackInterface.OnEndClick;
            }
            m_Wrapper.m_MouseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @StartClick.started += instance.OnStartClick;
                @StartClick.performed += instance.OnStartClick;
                @StartClick.canceled += instance.OnStartClick;
                @EndClick.started += instance.OnEndClick;
                @EndClick.performed += instance.OnEndClick;
                @EndClick.canceled += instance.OnEndClick;
            }
        }
    }
    public MouseActions @Mouse => new MouseActions(this);

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private IKeyboardActions m_KeyboardActionsCallbackInterface;
    private readonly InputAction m_Keyboard_add;
    private readonly InputAction m_Keyboard_remove;
    public struct KeyboardActions
    {
        private @AllInput m_Wrapper;
        public KeyboardActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @add => m_Wrapper.m_Keyboard_add;
        public InputAction @remove => m_Wrapper.m_Keyboard_remove;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterface != null)
            {
                @add.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAdd;
                @add.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAdd;
                @add.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAdd;
                @remove.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRemove;
                @remove.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRemove;
                @remove.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRemove;
            }
            m_Wrapper.m_KeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @add.started += instance.OnAdd;
                @add.performed += instance.OnAdd;
                @add.canceled += instance.OnAdd;
                @remove.started += instance.OnRemove;
                @remove.performed += instance.OnRemove;
                @remove.canceled += instance.OnRemove;
            }
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);

    // BuildMode
    private readonly InputActionMap m_BuildMode;
    private IBuildModeActions m_BuildModeActionsCallbackInterface;
    private readonly InputAction m_BuildMode_remove;
    private readonly InputAction m_BuildMode_add;
    private readonly InputAction m_BuildMode_rotate;
    private readonly InputAction m_BuildMode_delete;
    private readonly InputAction m_BuildMode_changeCell;
    public struct BuildModeActions
    {
        private @AllInput m_Wrapper;
        public BuildModeActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @remove => m_Wrapper.m_BuildMode_remove;
        public InputAction @add => m_Wrapper.m_BuildMode_add;
        public InputAction @rotate => m_Wrapper.m_BuildMode_rotate;
        public InputAction @delete => m_Wrapper.m_BuildMode_delete;
        public InputAction @changeCell => m_Wrapper.m_BuildMode_changeCell;
        public InputActionMap Get() { return m_Wrapper.m_BuildMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildModeActions set) { return set.Get(); }
        public void SetCallbacks(IBuildModeActions instance)
        {
            if (m_Wrapper.m_BuildModeActionsCallbackInterface != null)
            {
                @remove.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRemove;
                @remove.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRemove;
                @remove.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRemove;
                @add.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnAdd;
                @add.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnAdd;
                @add.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnAdd;
                @rotate.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRotate;
                @rotate.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRotate;
                @rotate.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnRotate;
                @delete.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnDelete;
                @delete.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnDelete;
                @delete.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnDelete;
                @changeCell.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnChangeCell;
                @changeCell.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnChangeCell;
                @changeCell.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnChangeCell;
            }
            m_Wrapper.m_BuildModeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @remove.started += instance.OnRemove;
                @remove.performed += instance.OnRemove;
                @remove.canceled += instance.OnRemove;
                @add.started += instance.OnAdd;
                @add.performed += instance.OnAdd;
                @add.canceled += instance.OnAdd;
                @rotate.started += instance.OnRotate;
                @rotate.performed += instance.OnRotate;
                @rotate.canceled += instance.OnRotate;
                @delete.started += instance.OnDelete;
                @delete.performed += instance.OnDelete;
                @delete.canceled += instance.OnDelete;
                @changeCell.started += instance.OnChangeCell;
                @changeCell.performed += instance.OnChangeCell;
                @changeCell.canceled += instance.OnChangeCell;
            }
        }
    }
    public BuildModeActions @BuildMode => new BuildModeActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_action0;
    private readonly InputAction m_Debug_action1;
    private readonly InputAction m_Debug_action2;
    private readonly InputAction m_Debug_action3;
    private readonly InputAction m_Debug_action4;
    private readonly InputAction m_Debug_action5;
    private readonly InputAction m_Debug_action6;
    private readonly InputAction m_Debug_action7;
    private readonly InputAction m_Debug_action8;
    private readonly InputAction m_Debug_action9;
    public struct DebugActions
    {
        private @AllInput m_Wrapper;
        public DebugActions(@AllInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @action0 => m_Wrapper.m_Debug_action0;
        public InputAction @action1 => m_Wrapper.m_Debug_action1;
        public InputAction @action2 => m_Wrapper.m_Debug_action2;
        public InputAction @action3 => m_Wrapper.m_Debug_action3;
        public InputAction @action4 => m_Wrapper.m_Debug_action4;
        public InputAction @action5 => m_Wrapper.m_Debug_action5;
        public InputAction @action6 => m_Wrapper.m_Debug_action6;
        public InputAction @action7 => m_Wrapper.m_Debug_action7;
        public InputAction @action8 => m_Wrapper.m_Debug_action8;
        public InputAction @action9 => m_Wrapper.m_Debug_action9;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @action0.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction0;
                @action0.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction0;
                @action0.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction0;
                @action1.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction1;
                @action1.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction1;
                @action1.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction1;
                @action2.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction2;
                @action2.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction2;
                @action2.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction2;
                @action3.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction3;
                @action3.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction3;
                @action3.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction3;
                @action4.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction4;
                @action4.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction4;
                @action4.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction4;
                @action5.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction5;
                @action5.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction5;
                @action5.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction5;
                @action6.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction6;
                @action6.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction6;
                @action6.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction6;
                @action7.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction7;
                @action7.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction7;
                @action7.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction7;
                @action8.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction8;
                @action8.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction8;
                @action8.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction8;
                @action9.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction9;
                @action9.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction9;
                @action9.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAction9;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @action0.started += instance.OnAction0;
                @action0.performed += instance.OnAction0;
                @action0.canceled += instance.OnAction0;
                @action1.started += instance.OnAction1;
                @action1.performed += instance.OnAction1;
                @action1.canceled += instance.OnAction1;
                @action2.started += instance.OnAction2;
                @action2.performed += instance.OnAction2;
                @action2.canceled += instance.OnAction2;
                @action3.started += instance.OnAction3;
                @action3.performed += instance.OnAction3;
                @action3.canceled += instance.OnAction3;
                @action4.started += instance.OnAction4;
                @action4.performed += instance.OnAction4;
                @action4.canceled += instance.OnAction4;
                @action5.started += instance.OnAction5;
                @action5.performed += instance.OnAction5;
                @action5.canceled += instance.OnAction5;
                @action6.started += instance.OnAction6;
                @action6.performed += instance.OnAction6;
                @action6.canceled += instance.OnAction6;
                @action7.started += instance.OnAction7;
                @action7.performed += instance.OnAction7;
                @action7.canceled += instance.OnAction7;
                @action8.started += instance.OnAction8;
                @action8.performed += instance.OnAction8;
                @action8.canceled += instance.OnAction8;
                @action9.started += instance.OnAction9;
                @action9.performed += instance.OnAction9;
                @action9.canceled += instance.OnAction9;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnInventory(InputAction.CallbackContext context);
        void OnCrafting(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnBuildMode(InputAction.CallbackContext context);
    }
    public interface IMouseActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnStartClick(InputAction.CallbackContext context);
        void OnEndClick(InputAction.CallbackContext context);
    }
    public interface IKeyboardActions
    {
        void OnAdd(InputAction.CallbackContext context);
        void OnRemove(InputAction.CallbackContext context);
    }
    public interface IBuildModeActions
    {
        void OnRemove(InputAction.CallbackContext context);
        void OnAdd(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
        void OnChangeCell(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnAction0(InputAction.CallbackContext context);
        void OnAction1(InputAction.CallbackContext context);
        void OnAction2(InputAction.CallbackContext context);
        void OnAction3(InputAction.CallbackContext context);
        void OnAction4(InputAction.CallbackContext context);
        void OnAction5(InputAction.CallbackContext context);
        void OnAction6(InputAction.CallbackContext context);
        void OnAction7(InputAction.CallbackContext context);
        void OnAction8(InputAction.CallbackContext context);
        void OnAction9(InputAction.CallbackContext context);
    }
}
